--- 
site: bookdown::bookdown_site   # needed for R studio integraion (Build tab)

#
# Book Metadata
#
title: "Time Series with Simulations and R"
author: "Darrin Speegle"
date: "`r Sys.Date()`"

   # description field is metadata in the html files that will show up on
   # facebook, twitter, and other social media.  It does not appear in the book text.
description: >-
   Time Series with Simulations and R by Darrin Speegle.
   This textbook is ideal for a first time series course with only an intro prob/stats
   course as a prerequisite. 
   Assumes knowledge from Foundations of Statistics with R by Speegle and Clair.
   It explores time series through simulations of the main results and models.

# Settings for CRC's krantz.cls
# (more specifically, Yihui Xie's mod of krantz.cls)
documentclass: krantz # use 'book' for default book documentclass
classoption: krantz2  # gives 5.5 x 8.5 page area.  Default is krantz1, 4.5 x 7.5

---
\mainmatter

# Preface

This book consists of notes written for STAT 4840 at Saint Louis University. The prerequisite for this class is Calculus I and II, and [STAT 3850](https://math.slu.edu/~speegled/_book). We are following the outline of topics in Introductory Time Series with R by Cowpertwait and Metcalfe, and these notes are intended to supplement that text. We will encounter topics that require more background than is typically covered in STAT 3850. When that happens, I will cover in detail the **first thing** that is beyond 3850 that you would need to fully understand the new topic. The rest of the things that you need to know to undertand that topic will be swept under the rug, and presented as facts that you will just accept. This is a compromise position. I don't think it is reasonable to ask you to learn 4 different things to understand one topic in time series. However, if we never cover the extra things, then you will never be any closer to fully understanding the topics. My hope is that each time you encounter these topics, you will take it on yourself to learn the next thing you would need to know to fully understand the topic, and eventually master it in this way.

Data for this book comes from the R package `tswrdata` which can be installed using `remotes::install_github(repo = "speegled/tswrdata")`. If you do not have `remotes` already installed, you will first need to run `library(remotes)`.